# Generated by Django 4.0.4 on 2022-06-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccextractorProcess', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='video',
        ),
    ]
